# Supabase Edge Function Configuration

[functions]
  [functions.run-monitoring-cycle]
    verify_jwt = false
    import_map = "./import_map.json"
  
  [functions.discover-new-sources]
    verify_jwt = false
    import_map = "./import_map.json"
  
  [functions.scrape-source-content]
    verify_jwt = false
    import_map = "./import_map.json"
  
  [functions.process-content-with-ai]
    verify_jwt = false
    import_map = "./import_map.json"
  
  [functions.generate-alert]
    verify_jwt = false
    import_map = "./import_map.json"
